### ISSUE TITLE
DelayedLauncher cannot run on Catalina (10.15.7)

### ISSUE THREAD

**Issue by OldhamMade** [taoeffect/DelayedLauncher#4]
DelayedLauncher cannot run on Catalina (10.15.7) due to changes in supporting 32bit applications.

Could we get a 64bit update?

**Comment by taoeffect** [comment]
Sure! Download the code and recompile it yourself!

**Comment by taoeffect** [comment]
And my apologies for the curt reply, but I have zero time to spend on this, and that is exactly why I open-sourced the app, so that whoever wants to update it, can do it themselves.
